"""Configuration multilingue du générateur d'apps (S37).

Une app livrée est générée dans **une** langue, fixée à la livraison (une app = la
langue de l'entreprise cliente). Le français reste le défaut ET le repli : toute
langue inconnue retombe sur `fr`, et toute clé manquante dans une traduction
retombe sur sa valeur française (repli par clé — honnête : pas de texte vide).

Deux usages :
- `consigne_langue(langue)` : directive injectée dans les prompts LLM pour forcer la
  langue des VALEURS produites (le contenu sur-mesure : libellés, résumés, actions…).
- `textes(langue)` : dictionnaire des libellés STATIQUES du gabarit (le châssis :
  navigation, boutons CRUD, modal, messages JS), repris par `gabarit.py`.
"""

LANGUE_DEFAUT = "fr"

# code ISO 639-1 → nom lisible (pour instruire le LLM). 'ar' arrivera en S44 (RTL).
_NOMS = {
    "fr": "français",
    "en": "anglais (English)",
    "es": "espagnol (Español)",
    "ar": "arabe (العربية)",
}


def normaliser_langue(langue) -> str:
    """Ramène une entrée libre à un code supporté ; repli `fr` si inconnu."""
    code = (str(langue or "").strip().lower())[:2]
    return code if code in _NOMS else LANGUE_DEFAUT


def nom_langue(langue) -> str:
    return _NOMS[normaliser_langue(langue)]


def consigne_langue(langue) -> str:
    """Directive de langue de sortie à AJOUTER à un prompt LLM.

    Vide pour le français (comportement historique inchangé). Pour les autres
    langues : impose la langue des valeurs texte, en gardant les CLÉS JSON en
    français (elles sont structurelles, lues par le gabarit)."""
    code = normaliser_langue(langue)
    if code == "fr":
        return ""
    nom = _NOMS[code]
    return (
        f"\n\nLANGUE DE SORTIE — IMPÉRATIF : rédige TOUTES les valeurs de texte "
        f"(noms, libellés, titres, descriptions, résumés, messages, options de statut) "
        f"en {nom}. Garde les CLÉS du JSON strictement inchangées (en français, telles "
        f"que demandées). N'utilise aucune autre langue que {nom} dans les valeurs."
    )


# ── Libellés statiques du châssis (gabarit) ───────────────────────────────────────
# Clés communes ; seul `fr` est exhaustif. Les autres langues peuvent être partielles :
# `textes()` complète automatiquement les trous avec le français (repli par clé).

_FR = {
    # locale JS pour toLocaleString (formatage nombres/montants)
    "locale": "fr-FR",
    # navigation (catégories de la sidebar)
    "cat_pilotage": "Pilotage",
    "cat_outils": "Outils",
    "cat_analyse": "Analyse stratégique",
    "cat_extensions": "Extensions",
    # châssis & footer
    "genere_par": "Généré par Workplace",
    # boutons / en-têtes CRUD
    "actions": "Actions",
    "ajouter": "Ajouter",
    "annuler": "Annuler",
    "enregistrer": "Enregistrer",
    "modal_nouveau": "Nouveau",
    "prefixe_nouveau": "Nouveau : ",
    "prefixe_modifier": "Modifier : ",
    # libellés de vues (sidebar) + en-têtes de page
    "vue_tableau_bord": "Tableau de bord",
    "entete_tableau_bord": "Tableau de bord — ",
    "vue_app_proposee": "Application proposée",
    "entete_app_proposee": "Application sur-mesure proposée",
    "vue_territoire": "Territoire",
    "entete_territoire": "Territoire de l'entreprise",
    "vue_flux": "Flux",
    "entete_flux": "Flux & Processus",
    "vue_problemes": "Problèmes",
    "entete_problemes": "Analyse des problèmes",
    "vue_priorites": "Priorités",
    "entete_priorites": "Priorités & Roadmap",
    # défauts de plan (repli si le LLM n'a rien fourni)
    "defaut_sous_titre": "Tableau de bord stratégique",
    "defaut_message": "Bienvenue dans votre tableau de bord",
    # messages JS interactifs
    "js_connexion_requise": "Connexion requise",
    "js_acces_reserve": "Accès réservé aux comptes de l'entreprise.",
    "js_se_connecter": "Se connecter",
    "js_echec_connexion": "Échec de connexion",
    "js_utilisateur": "Utilisateur",
    "js_se_deconnecter": "Se déconnecter",
    "js_serveur_injoignable": "Serveur de données injoignable. Vérifiez que la brique « donnees » est démarrée.",
    "js_aucun_enregistrement": "Aucun enregistrement — cliquez sur « Ajouter ».",
    "js_confirmer_suppression": "Supprimer cet enregistrement ?",
    "js_echec_suppression": "Échec de la suppression",
    "js_echec_enregistrement": "Échec de l'enregistrement",
    "js_pareto_part_ca": "Part du CA (%)",
    "js_pareto_part_temps": "Part du temps (%)",
    "js_pareto_cumul_ca": "Cumul CA (%)",
}

_EN = {
    "locale": "en-US",
    "cat_pilotage": "Steering",
    "cat_outils": "Tools",
    "cat_analyse": "Strategic analysis",
    "cat_extensions": "Extensions",
    "genere_par": "Generated by Workplace",
    "actions": "Actions",
    "ajouter": "Add",
    "annuler": "Cancel",
    "enregistrer": "Save",
    "modal_nouveau": "New",
    "prefixe_nouveau": "New: ",
    "prefixe_modifier": "Edit: ",
    "vue_tableau_bord": "Dashboard",
    "entete_tableau_bord": "Dashboard — ",
    "vue_app_proposee": "Proposed application",
    "entete_app_proposee": "Tailored application proposed",
    "vue_territoire": "Territory",
    "entete_territoire": "Company territory",
    "vue_flux": "Flows",
    "entete_flux": "Flows & Processes",
    "vue_problemes": "Issues",
    "entete_problemes": "Issue analysis",
    "vue_priorites": "Priorities",
    "entete_priorites": "Priorities & Roadmap",
    "defaut_sous_titre": "Strategic dashboard",
    "defaut_message": "Welcome to your dashboard",
    "js_connexion_requise": "Sign-in required",
    "js_acces_reserve": "Access restricted to company accounts.",
    "js_se_connecter": "Sign in",
    "js_echec_connexion": "Sign-in failed",
    "js_utilisateur": "User",
    "js_se_deconnecter": "Sign out",
    "js_serveur_injoignable": "Data server unreachable. Make sure the « donnees » brick is running.",
    "js_aucun_enregistrement": "No records yet — click « Add ».",
    "js_confirmer_suppression": "Delete this record?",
    "js_echec_suppression": "Deletion failed",
    "js_echec_enregistrement": "Save failed",
    "js_pareto_part_ca": "Revenue share (%)",
    "js_pareto_part_temps": "Time share (%)",
    "js_pareto_cumul_ca": "Cumulative revenue (%)",
}

_ES = {
    "locale": "es-ES",
    "cat_pilotage": "Dirección",
    "cat_outils": "Herramientas",
    "cat_analyse": "Análisis estratégico",
    "cat_extensions": "Extensiones",
    "genere_par": "Generado por Workplace",
    "actions": "Acciones",
    "ajouter": "Añadir",
    "annuler": "Cancelar",
    "enregistrer": "Guardar",
    "modal_nouveau": "Nuevo",
    "prefixe_nouveau": "Nuevo: ",
    "prefixe_modifier": "Editar: ",
    "vue_tableau_bord": "Panel de control",
    "entete_tableau_bord": "Panel de control — ",
    "vue_app_proposee": "Aplicación propuesta",
    "entete_app_proposee": "Aplicación a medida propuesta",
    "vue_territoire": "Territorio",
    "entete_territoire": "Territorio de la empresa",
    "vue_flux": "Flujos",
    "entete_flux": "Flujos y procesos",
    "vue_problemes": "Problemas",
    "entete_problemes": "Análisis de problemas",
    "vue_priorites": "Prioridades",
    "entete_priorites": "Prioridades y hoja de ruta",
    "defaut_sous_titre": "Panel estratégico",
    "defaut_message": "Bienvenido a su panel",
    "js_connexion_requise": "Inicio de sesión requerido",
    "js_acces_reserve": "Acceso reservado a las cuentas de la empresa.",
    "js_se_connecter": "Iniciar sesión",
    "js_echec_connexion": "Error de inicio de sesión",
    "js_utilisateur": "Usuario",
    "js_se_deconnecter": "Cerrar sesión",
    "js_serveur_injoignable": "Servidor de datos inaccesible. Compruebe que el módulo « donnees » esté iniciado.",
    "js_aucun_enregistrement": "Sin registros — haga clic en « Añadir ».",
    "js_confirmer_suppression": "¿Eliminar este registro?",
    "js_echec_suppression": "Error al eliminar",
    "js_echec_enregistrement": "Error al guardar",
    "js_pareto_part_ca": "Cuota de ingresos (%)",
    "js_pareto_part_temps": "Cuota de tiempo (%)",
    "js_pareto_cumul_ca": "Ingresos acumulados (%)",
}

# 'ar' : ajouté en S44 (RTL). Pour l'instant il hérite entièrement du français par le
# repli de `textes()` (honnête : aucune fausse traduction).
_TABLE = {"fr": _FR, "en": _EN, "es": _ES}

# Sous-ensemble de clés exposées au JS embarqué (objet `T` côté navigateur) :
# tous les messages `js_*`, les préfixes du modal CRUD, et la locale de formatage.
_CLES_JS = ([k for k in _FR if k.startswith("js_")]
            + ["locale", "prefixe_nouveau", "prefixe_modifier"])


def textes(langue) -> dict:
    """Dictionnaire de libellés pour la langue demandée, avec repli par clé sur `fr`."""
    code = normaliser_langue(langue)
    if code == "fr":
        return dict(_FR)
    return {**_FR, **_TABLE.get(code, {})}


def textes_js(langue) -> dict:
    """Le sous-ensemble de libellés nécessaire au JS embarqué du gabarit."""
    t = textes(langue)
    return {k: t[k] for k in _CLES_JS}
