"""Socle multilingue des apps livrées (S37) — aucun réseau, aucun LLM.

Écrit à l'origine comme script autonome (`def run()`), donc jamais exécuté par le filet.
Converti en tests pytest le 2026-07-28 — les 7 scénarios sont conservés à l'identique.
"""
import langues
from gabarit import generer_html
from prompts import prompt_plan_app, prompt_revue, prompt_schema_module

AUDIT = {"nom_entreprise": "Atelier Lumière",
         "territoire": {"glossaire_metier": [{"terme_entreprise": "Composition"}]}}
PLAN = {"nom_app": "LumièreOps", "secteur": "Artisanat",
        "entites": [{"id": "devis", "nom": "Devis",
                     "champs": [{"cle": "montant", "label": "Montant", "type": "montant"}]}]}


def test_normalisation_codes_connus_gardes_inconnu_replie_sur_fr():
    assert langues.normaliser_langue("EN") == "en"
    assert langues.normaliser_langue("es-ES") == "es"
    assert langues.normaliser_langue("klingon") == "fr"
    assert langues.normaliser_langue(None) == "fr"


def test_consigne_llm_vide_en_fr_imperative_et_nommee_en_en():
    assert langues.consigne_langue("fr") == "", "le français ne doit RIEN injecter (historique)"
    c_en = langues.consigne_langue("en")
    assert "anglais" in c_en and "IMPÉRATIF" in c_en, c_en
    assert "CLÉS" in c_en, "doit demander de garder les clés JSON inchangées"
    assert langues.consigne_langue("zzz") == "", "langue inconnue → repli fr → consigne vide"


def test_les_prompts_portent_la_consigne_en_en_es_et_rien_en_fr():
    assert langues.consigne_langue("en") in prompt_plan_app(AUDIT, "en")
    assert "anglais" in prompt_plan_app(AUDIT, "en")
    assert langues.consigne_langue("en") in prompt_revue(AUDIT, PLAN, {}, [], "en")
    assert langues.consigne_langue("es") in prompt_schema_module("X", "Module", "raison", AUDIT, "es")
    assert "IMPÉRATIF" not in prompt_plan_app(AUDIT), "défaut 'fr' : aucune consigne ajoutée"


def test_gabarit_fr_non_regression():
    html = generer_html(AUDIT, PLAN, langue="fr")
    assert '<html lang="fr">' in html, "lang fr"
    assert "Généré par Workplace" in html
    assert ">Ajouter<" in html and ">Enregistrer<" in html and ">Annuler<" in html
    assert "fr-FR" in html, "locale JS fr-FR"


def test_gabarit_en_chassis_traduit_et_objet_js_localise():
    html = generer_html(AUDIT, PLAN, langue="en")
    assert '<html lang="en">' in html, "lang en"
    assert "Generated by Workplace" in html, "footer EN"
    assert ">Add<" in html and ">Save<" in html and ">Cancel<" in html, "boutons EN"
    assert "Steering" in html and "Tools" in html, "catégories nav EN"
    assert "Généré par Workplace" not in html, "aucun résidu FR dans le châssis"
    assert "en-US" in html, "locale JS en-US"
    assert "Sign-in required" in html, "message JS d'auth traduit"


def test_gabarit_es_chassis_traduit_et_objet_js_localise():
    html = generer_html(AUDIT, PLAN, langue="es")
    assert '<html lang="es">' in html, "lang es"
    assert "Generado por Workplace" in html, "footer ES"
    assert ">Añadir<" in html and ">Guardar<" in html and ">Cancelar<" in html, "boutons ES"
    assert "Dirección" in html and "Herramientas" in html, "catégories nav ES"
    assert "Généré par Workplace" not in html, "aucun résidu FR dans le châssis"
    assert "es-ES" in html, "locale JS es-ES"
    assert "Inicio de sesión requerido" in html, "message JS d'auth traduit"


def test_gabarit_langue_inconnue_replie_sur_le_chassis_francais():
    """Le repli doit produire une app en français, jamais des libellés vides."""
    html = generer_html(AUDIT, PLAN, langue="zzz")
    assert '<html lang="fr">' in html, "langue inconnue → lang fr"
    assert "Généré par Workplace" in html
