"""Preuve offline du socle multilingue des apps livrées (S37) — aucun réseau, aucun LLM.

On vérifie la chaîne langue côté générateur, sans Gateway :

  1. **normalisation / repli** : codes connus conservés, inconnus → 'fr' (repli honnête) ;
  2. **consigne LLM** : vide en 'fr' (comportement historique), impérative et nommant la
     langue cible pour 'en'/'es', clés JSON gardées en français ;
  3. **prompts** : `prompt_plan_app`/`prompt_revue`/`prompt_schema_module` portent la
     consigne de langue quand on la demande, et rien de spécial en 'fr' ;
  4. **gabarit FR (non-régression)** : `lang="fr"`, châssis en français, JS localisé présent ;
  5. **gabarit EN** : `lang="en"`, châssis traduit (navigation, boutons, modal, footer),
     objet JS `T` en anglais avec locale en-US ;
  6. **gabarit ES** : `lang="es"`, châssis espagnol (Añadir/Guardar/Cancelar, Dirección),
     objet JS `T` en espagnol avec locale es-ES ;
  7. **gabarit repli** : langue inconnue → châssis français (aucun texte vide).

Lancer : `python3 test_langues.py`.
"""
import json

import langues
from prompts import prompt_plan_app, prompt_revue, prompt_schema_module
from gabarit import generer_html


AUDIT = {"nom_entreprise": "Atelier Lumière",
         "territoire": {"glossaire_metier": [{"terme_entreprise": "Composition"}]}}
PLAN = {"nom_app": "LumièreOps", "secteur": "Artisanat",
        "entites": [{"id": "devis", "nom": "Devis",
                     "champs": [{"cle": "montant", "label": "Montant", "type": "montant"}]}]}


def run():
    ok = 0

    # 1) Normalisation + repli.
    assert langues.normaliser_langue("EN") == "en"
    assert langues.normaliser_langue("es-ES") == "es"
    assert langues.normaliser_langue("klingon") == "fr"
    assert langues.normaliser_langue(None) == "fr"
    print("✅ 1. normalisation : codes connus gardés, inconnu/None → 'fr' (repli)")
    ok += 1

    # 2) Consigne de langue pour le LLM.
    assert langues.consigne_langue("fr") == "", "le français ne doit RIEN injecter (historique)"
    c_en = langues.consigne_langue("en")
    assert "anglais" in c_en and "IMPÉRATIF" in c_en, c_en
    assert "CLÉS" in c_en, "doit demander de garder les clés JSON inchangées"
    assert langues.consigne_langue("zzz") == "", "langue inconnue → repli fr → consigne vide"
    print("✅ 2. consigne LLM : vide en 'fr', impérative et nommée en 'en', clés JSON préservées")
    ok += 1

    # 3) Prompts paramétrés.
    assert langues.consigne_langue("en") in prompt_plan_app(AUDIT, "en")
    assert "anglais" in prompt_plan_app(AUDIT, "en")
    assert langues.consigne_langue("en") in prompt_revue(AUDIT, PLAN, {}, [], "en")
    assert langues.consigne_langue("es") in prompt_schema_module("X", "Module", "raison", AUDIT, "es")
    # défaut 'fr' : aucune consigne ajoutée
    assert "IMPÉRATIF" not in prompt_plan_app(AUDIT)
    print("✅ 3. prompts : consigne portée en 'en'/'es', rien d'ajouté en 'fr' (défaut)")
    ok += 1

    # 4) Gabarit FR — non-régression.
    html_fr = generer_html(AUDIT, PLAN, langue="fr")
    assert '<html lang="fr">' in html_fr, "lang fr"
    assert "Généré par Workplace" in html_fr
    assert ">Ajouter<" in html_fr and ">Enregistrer<" in html_fr and ">Annuler<" in html_fr
    assert '"fr-FR"' in html_fr or "fr-FR" in html_fr, "locale JS fr-FR"
    print("✅ 4. gabarit FR : lang=fr, châssis français, JS localisé présent (non-régression)")
    ok += 1

    # 5) Gabarit EN — châssis traduit + objet JS T.
    html_en = generer_html(AUDIT, PLAN, langue="en")
    assert '<html lang="en">' in html_en, "lang en"
    assert "Generated by Workplace" in html_en, "footer EN"
    assert ">Add<" in html_en and ">Save<" in html_en and ">Cancel<" in html_en, "boutons EN"
    assert "Steering" in html_en and "Tools" in html_en, "catégories nav EN"
    assert "Généré par Workplace" not in html_en, "aucun résidu FR dans le châssis"
    # l'objet JS T doit être injecté avec la locale anglaise
    assert "en-US" in html_en, "locale JS en-US"
    assert "Sign-in required" in html_en, "message JS d'auth traduit"
    print("✅ 5. gabarit EN : lang=en, navigation/boutons/modal/footer traduits, JS T en-US")
    ok += 1

    # 6) Gabarit ES — châssis espagnol + objet JS T.
    html_es = generer_html(AUDIT, PLAN, langue="es")
    assert '<html lang="es">' in html_es, "lang es"
    assert "Generado por Workplace" in html_es, "footer ES"
    assert ">Añadir<" in html_es and ">Guardar<" in html_es and ">Cancelar<" in html_es, "boutons ES"
    assert "Dirección" in html_es and "Herramientas" in html_es, "catégories nav ES"
    assert "Généré par Workplace" not in html_es, "aucun résidu FR dans le châssis"
    assert "es-ES" in html_es, "locale JS es-ES"
    assert "Inicio de sesión requerido" in html_es, "message JS d'auth traduit"
    print("✅ 6. gabarit ES : lang=es, navigation/boutons/modal/footer traduits, JS T es-ES")
    ok += 1

    # 7) Gabarit repli — langue inconnue → châssis français, jamais de vide.
    html_xx = generer_html(AUDIT, PLAN, langue="zzz")
    assert '<html lang="fr">' in html_xx, "langue inconnue → lang fr"
    assert "Généré par Workplace" in html_xx
    print("✅ 7. gabarit repli : langue inconnue → châssis FR (aucun texte vide)")
    ok += 1

    print(f"\n{ok}/7 scénarios OK")
    return ok


if __name__ == "__main__":
    import sys
    sys.exit(0 if run() == 7 else 1)
